# Generated by Django 3.0.5 on 2020-05-09 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('a', 'Kho Cây Giống'), ('b', 'Kho Sản Phẩm'), ('c', 'Kho Vật Tư'), ('d', 'Kho Tồn')], default='a', max_length=100)),
                ('product_name', models.CharField(choices=[('a', 'Bắp Cải Xanh'), ('b', 'Cần Tây'), ('c', 'Xà Lách'), ('d', 'Cà Chua'), ('e', 'Củ Cải Trắng')], default='a', max_length=150)),
                ('amount', models.IntegerField(default='1')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('position', models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán')], default='a', max_length=100)),
                ('phone', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=70)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
