# Generated by Django 3.0.5 on 2020-05-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200516_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_id',
            new_name='farm_id',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='house_id',
            new_name='farm_id',
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_position',
            field=models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán')], default='a', max_length=100),
        ),
    ]
