# Generated by Django 3.0.5 on 2020-06-09 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_cruduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thu2', models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], default='x', max_length=100)),
                ('thu3', models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], default='x', max_length=100)),
                ('thu4', models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], default='x', max_length=100)),
                ('thu5', models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], default='x', max_length=100)),
                ('thu6', models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], default='x', max_length=100)),
                ('thu7', models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], default='x', max_length=100)),
                ('chunhat', models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], default='x', max_length=100)),
                ('farm_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CrudUser',
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_position',
            field=models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], default='x', max_length=100),
        ),
    ]
