# Generated by Django 3.0.5 on 2020-06-09 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_auto_20200609_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='chunhat',
            new_name='posittion',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='thu2',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='thu3',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='thu4',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='thu5',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='thu6',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='thu7',
        ),
        migrations.AddField(
            model_name='calendar',
            name='day',
            field=models.CharField(choices=[('c', 'Thứ 2'), ('d', 'Thứ 3'), ('e', 'Thứ 4'), ('f', 'Thứ 5'), ('g', 'Thứ 6'), ('h', 'Thứ 7'), ('j', 'Chủ Nhật')], default='c', max_length=10),
        ),
        migrations.AddField(
            model_name='calendar',
            name='time',
            field=models.CharField(choices=[('a', 'Ca 1 (7h30 - 11h30)'), ('b', 'Ca 2 (13h30 - 16h30)')], default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
