# Generated by Django 3.0.5 on 2020-06-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200609_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='posittion',
            new_name='chunhat',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='day',
        ),
        migrations.AddField(
            model_name='calendar',
            name='thu2',
            field=models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='calendar',
            name='thu3',
            field=models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='calendar',
            name='thu4',
            field=models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='calendar',
            name='thu5',
            field=models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='calendar',
            name='thu6',
            field=models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='calendar',
            name='thu7',
            field=models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], default='x', max_length=100),
        ),
    ]
