# Generated by Django 3.0.5 on 2020-06-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200609_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='chunhat',
            field=models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='thu2',
            field=models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='thu3',
            field=models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='thu4',
            field=models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='thu5',
            field=models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='thu6',
            field=models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='thu7',
            field=models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='time',
            field=models.CharField(choices=[('a', 'Ca 1 (7h30 - 11h30)'), ('b', 'Ca 2 (13h30 - 16h30)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_position',
            field=models.CharField(choices=[('a', 'Quản Lý Kho'), ('b', 'Quản Lý Bán Hàng'), ('c', 'Quản Lý Sản Xuất'), ('d', 'Quản Lý Kế Toán'), ('x', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(choices=[('a', 'Kho Cây Giống'), ('b', 'Kho Sản Phẩm'), ('c', 'Kho Vật Tư'), ('d', 'Kho Tồn')], max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='product_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
