# Generated by Django 3.0.5 on 2020-06-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_staff_staff_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_off',
            field=models.IntegerField(default=0),
        ),
    ]
