# Generated by Django 3.0.5 on 2020-06-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_staff_staff_off'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
