# Generated by Django 3.0.5 on 2020-04-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
