# Generated by Django 3.0.5 on 2020-04-18 14:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0007_auto_20200418_2102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileUser1',
            new_name='UserProfile',
        ),
    ]
