# Generated by Django 3.0.5 on 2020-04-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20200419_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='nongtrai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nongtrai', models.CharField(default=33308, max_length=5, unique=True)),
                ('ten_nongtrai', models.CharField(max_length=200)),
            ],
        ),
    ]
