# Generated by Django 3.0.5 on 2020-04-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_nongtrai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nongtrai',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='farm_id',
            field=models.CharField(default='L4YQLJCC', max_length=8, unique=True),
        ),
    ]
