# Generated by Django 3.0.5 on 2020-04-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20200419_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='farm_id',
            field=models.CharField(default='0BCNL7NH', max_length=8, unique=True),
        ),
    ]
