# Generated by Django 3.0.5 on 2020-04-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20200419_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='farm_id',
            field=models.CharField(default='T9BT4FQS', max_length=8, unique=True),
        ),
    ]
