# Generated by Django 3.0.5 on 2020-04-21 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20200419_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.CharField(default='4JL95NIK', max_length=8, unique=True)),
                ('farm_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Farm'),
        ),
    ]
