# Generated by Django 3.0.5 on 2020-04-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20200421_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_id',
            field=models.CharField(default='OLSVKRWC', max_length=8, unique=True),
        ),
    ]
