# Generated by Django 3.0.5 on 2020-04-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_auto_20200421_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_id',
            field=models.CharField(default='HFP8JSWQ', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='farm_id',
            field=models.CharField(max_length=8),
        ),
    ]
