# Generated by Django 3.0.5 on 2020-04-21 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_auto_20200421_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farm_id',
        ),
        migrations.AddField(
            model_name='farm',
            name='id_farm',
            field=models.CharField(default='R3D18YXS', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='farm_id',
            field=models.CharField(default='NONE', max_length=8),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(default='C2WWQWEK', max_length=8, unique=True)),
                ('staff_name', models.CharField(default='', max_length=250)),
                ('staff_email', models.EmailField(max_length=250)),
                ('id_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Farm')),
            ],
        ),
    ]
