# Generated by Django 3.0.5 on 2020-05-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_auto_20200509_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='farm_name',
            field=models.CharField(default='Farm_name', max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='farm_id',
            field=models.CharField(default='9FET0S7T', max_length=8, unique=True),
        ),
    ]
