# Generated by Django 3.0.5 on 2020-05-09 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_auto_20200509_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='farm_id',
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(default='', max_length=250)),
                ('staff_phone', models.CharField(default='', max_length=10)),
                ('staff_email', models.EmailField(default='', max_length=70)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserProfile')),
            ],
        ),
    ]
