# Generated by Django 3.0.5 on 2020-05-09 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0022_auto_20200509_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staff_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staff_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staff_position',
            new_name='position',
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('a', 'Kho Cây Giống'), ('b', 'Kho Sản Phẩm'), ('c', 'Kho Vật Tư'), ('d', 'Kho Tồn')], default='a', max_length=100)),
                ('product', models.CharField(default='', max_length=150)),
                ('amount', models.IntegerField(default='1')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
