# Generated by Django 3.0.5 on 2020-05-09 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0023_auto_20200509_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='house_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
