# Generated by Django 3.0.5 on 2020-05-09 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0024_auto_20200509_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='product',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='product_name',
            field=models.CharField(choices=[('a', 'Bắp Cải Xanh'), ('b', 'Cần Tây'), ('c', 'Xà Lách'), ('d', 'Cà Chua'), ('e', 'Củ Cải Trắng')], default='a', max_length=150),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
