# Generated by Django 3.0.5 on 2020-05-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_auto_20200509_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='house_id',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
